section.testimonials
Dmytro1573/itigers-project pull request #1
Opened 2023-10-28 18:11 UTC by Khalatska

2023-10-29 21:32 UTC, Dmytro1573 commented on src/css/testimonials.css
> +position: relative;
Тут треба задати властивість padding : 54px 22px 18px 22px

2023-10-29 21:33 UTC, Dmytro1573 commented on src/css/testimonials.css
> +margin-top: 54px;
Тут прибрати властивість margin top: 54px;

2023-10-29 21:39 UTC, Dmytro1573 commented on src/css/testimonials.css
> +margin-top: 54px;
Тут треба замінити властивість margin-top: 54 на padding-top: 54px

2023-10-29 21:47 UTC, Dmytro1573 commented on src/css/testimonials.css
> +padding-right: 18px;
Тут треба написати властивість padding: 0 22px 18px 22px;

2023-10-29 21:50 UTC, Dmytro1573 commented on src/css/testimonials.css
> +}
Тут треба змінити властивість line-height: normal на line-height: 1.3;
Також треба змінити властивість width: auto на  width: 291px;

2023-10-29 21:53 UTC, Dmytro1573 commented on src/css/testimonials.css
> +    padding-top: 81px;
Тут треба padding-top: 80px;

2023-10-29 22:01 UTC, Dmytro1573 commented on src/css/testimonials.css
> +        width: 306px;
Тут треба width: 307px

2023-10-29 22:39 UTC, Dmytro1573 commented on src/css/testimonials.css
> +        padding-bottom: 150px;
Тут треба добавити padding-right: 84px та padding-left: 84px 
Або просто написати padding: 150px 84px 150px 84px;

2023-10-29 22:42 UTC, Dmytro1573 commented on src/css/testimonials.css
> +
Тут виправити width: 306px на width: 307px і прибрати властивість margin

2023-10-29 22:46 UTC, Dmytro1573 commented on src/css/testimonials.css
> +}
Також додати клас .testimonial-list з властивістю gap: 26px;

2023-10-29 22:53 UTC, Dmytro1573 requested changes
Перевірив твою роботу

2023-10-30 07:31 UTC, Dmytro1573 commented on src/css/testimonials.css
> +        max-width: 1280px;
Тут в .container додай властивість padding: 0 50px 0 50px;

2023-10-30 11:37 UTC, Khalatska commented on src/css/testimonials.css
> +    padding-top: 81px;
Виправила

2023-10-30 11:38 UTC, Khalatska commented on src/css/testimonials.css
> +padding-right: 18px;
Виправила

2023-10-30 11:39 UTC, Khalatska commented on src/css/testimonials.css
> +margin-top: 54px;
Виправила

2023-10-30 11:39 UTC, Khalatska commented on src/css/testimonials.css
> +}
Виправила

2023-10-30 11:39 UTC, Khalatska commented on src/css/testimonials.css
> +        max-width: 1280px;
Виправила

2023-10-30 11:39 UTC, Khalatska commented on src/css/testimonials.css
> +}
Виправила

2023-11-01 19:09 UTC, Dmytro1573 approved these changes

2023-11-01 19:09 UTC, merged